SET(nice_gp-hik-core_SRC
./GMHIKernel.cpp
./IKMNoise.cpp
./kernels/IntersectionKernelFunction.cpp
./FastMinKernel.cpp
./GPHIKClassifier.cpp
./FMKGPHyperparameterOptimization.cpp
./Quantization.cpp
./VectorSorter.cpp
./algebra/LogDetApproxBaiAndGolub.cpp
./IKMLinearCombination.cpp
./GPLikelihoodApprox.cpp
./ImplicitKernelMatrix.cpp
./parameterizedFunctions/ParameterizedFunction.cpp
)

SET(nice_gp-hik-core_HDR
./kernels/GeneralizedIntersectionKernelFunction.h
./kernels/IntersectionKernelFunction.h
./kernels/GenericKernelFunction.h
./IKMNoise.h
./FeatureMatrixT.h
./GPHIKClassifier.h
./ImplicitKernelMatrix.h
./FMKGPHyperparameterOptimization.h
./FastMinKernel.h
./SortedVectorSparse.h
./Quantization.h
./tools.h
./algebra/LogDetApproxBaiAndGolub.h
./algebra/LogDetApprox.h
./VectorSorter.h
./GPLikelihoodApprox.h
./GMHIKernel.h
./IKMLinearCombination.h
./parameterizedFunctions/ParameterizedFunction.h
./parameterizedFunctions/PFExp.h
./parameterizedFunctions/PFMKL.h
./parameterizedFunctions/PFAbsExp.h
./parameterizedFunctions/PFWeightedDim.h
)

