#generated by find . -name "*.cpp" -ipath "*/tests/*" > testfiles.cmake.t 
SET(nice_gp-hik-core_TESTFILES_SRC 
./tests/TestVectorSorter.cpp
./tests/TestFeatureMatrixT.cpp
./tests/TestFastHIK.cpp
)

SET(nice_gp-hik-core_TESTFILES_HDR
./tests/TestFastHIK.h
./tests/TestVectorSorter.h
./tests/TestFeatureMatrixT.h
)